Todistus kortti lataa pdf painike
Opetushallitus/ludos pull request #119
Opened 2024-02-23 12:14 UTC by ChristianVilen

todo:

- [ ] pw testi

2024-02-26 10:07 UTC, visadb commented on playwright/non_parallel_tests/certificate/certificateList.spec.ts
> +      const checkSukoList = checkListAfterFilteringWithProvidedExam(page, list.exam)
Täähän ei oo enää suko-spesifi: pitäiskö nimetä vaan `checkList`?

2024-02-26 10:11 UTC, visadb commented on playwright/filterHelpers.ts
> +  async (expectedNumbersInCards: number[], contentSpecificAssert: Promise<void>): Promise<void> => {
contentSpecificAssertin kannattais varmaan olla tyyppiä `() => Promise<void>`

Jos se ei oo funkkari, niin toi tsekki laukeaa jo kutsujan toimesta eli mahdollisesti liian aikaisin.

2024-02-26 10:12 UTC, visadb commented on playwright/non_parallel_tests/certificate/certificateList.spec.ts
> +        checkPdfDownloadIconWorks(
Tän vois ekstraktoida constiin ja deduplikoida.

2024-02-26 10:14 UTC, visadb commented on web/src/components/content/list/certificate/CertificateCard.tsx
> +        </ExternalLink>
Harkitsitko ExternalLinkin sisällyttämistä PdfTag-komponenttiin? Äkkiseltään tuntuis kuuluvan enemmän sinne, mut toimiihan tääki :shrug:

2024-02-26 10:16 UTC, visadb requested changes
Ks. inline-kommentit

2024-02-26 10:18 UTC, ChristianVilen commented on web/src/components/content/list/certificate/CertificateCard.tsx
> +        </ExternalLink>
Hyvä idea! Laitetaan sinne :)

2024-02-27 10:21 UTC, visadb approved these changes
LGTM

2024-02-27 10:44 UTC, merged