Clean up attachments on update
Opetushallitus/ludos pull request #28
Opened 2023-06-29 08:38 UTC by ChristianVilen

2023-06-29 09:32 UTC, visadb requested changes
Jea, hyvä muutos! Ajatuksia ja kommentteja koodin seassa.

2023-06-29 09:32 UTC, visadb commented on server/src/main/kotlin/fi/oph/ludos/s3/S3Service.kt
> +    }
s3.deleteObjectin SdkExceptionin vois nappaa kii ja lokittaa errorin ja heittää poikkeuksen eteenpäin kuten getObjectissa. Saman muutoksen vois tehdä myös putObjectille. Vois helpottaa debuggailuja joskus. (Ja lisäks metodien kutsujan pitää myös muistaa ottaa SdkException kiinni.)

2023-06-29 09:32 UTC, visadb commented on server/src/main/kotlin/fi/oph/ludos/s3/S3Service.kt
> +    }
Näin yleisesti tän S3Servicen olemassaolon tarkoitus vähän mietityttää. Nyt tän pointtina näyttäis olevan varmistaa käynnistyksessä, että S3-yhteys pelaa ja lisäksi toimia hyvin ohuena wrapperina S3Clientille. S3Servicen käyttäjän pitää nyt tietää aika paljon tuon S3Clientin rajapinnan detaileista, kuten pitää osata ottaa kiinni SdkException, ja getObjectin käyttäjän pitää osata käpistellä `ResponseInputStream<GetObjectResponse>`.

En osaa sanoa, onko järkeä abstrahoida tuota S3Clientia yhtään enempää, eli ehkäpä just tällainen moduuli palvelee meitä parhaiten just nyt. Eli tää on oikeastaan jonkinlainen s3-helpperi, joka vähän helpottaa yleisiä käyttötapauksia.

Ehdotan, että nimi vaihdetaan olemaan `S3Helper`, ja annotaatio vaihdetaan `@Service` -> `@Component`, kun tuntuu vähän väärältä kutsua Service-tyyppistä asiaa repository-tasolta. (Toivottavasti myös `@Component` alustetaan, kun järjestelmä käynnistyy, jotta S3-yhteystsekki jatkaa toimintaansa).

(Jos tää abstrahoisi S3Clientin yksityiskohdat kunnolla, niin sit oikea nimi ois ehkä S3Repository, kun tää tekee just tallentamiseen ja tiedonhakuun liittyviä asioita :thinking: )

2023-06-29 09:32 UTC, visadb commented on server/src/test/kotlin/fi/oph/ludos/certificate/CertificateControllerTest.kt
> +            .andReturn().response.contentAsString
Ehkä tos myöhemmin vois myös tsekkaa, että preview oldFileKey:llä palauttaa 404

2023-06-29 10:00 UTC, ChristianVilen commented on server/src/test/kotlin/fi/oph/ludos/certificate/CertificateControllerTest.kt
> +        request.param("oldFileKey", oldFileKey)
ööhh ainii, mites me koodattii toi sillo? :D ois pitäny sittenki jättää kommenttiin ne poisto koodit

2023-06-29 10:03 UTC, ChristianVilen commented on server/src/test/kotlin/fi/oph/ludos/certificate/CertificateControllerTest.kt
> +        request.param("oldFileKey", oldFileKey)
Hups joo, korjattu käyttämään mockPart, olin jo unohtanu mite toi meni :P

2023-06-29 12:14 UTC, visadb commented on server/src/main/kotlin/fi/oph/ludos/certificate/CertificateRepository.kt
> +        if (oldFileKey != null) {
Pitikös tässä tsekata myös, ettei oldFileKey ole käytössä missään todistuksessa?

Jotta se tsekki ois tehokas, ja muutenkin yleisenä eheysvarmistuksena vois lisätä unique-constraintin certificate-tauluihin attachment_file_key-kolumniin. Tämä siis loisi indeksin, jonka ansiosta `SELECT foo FROM suko_certificate WHERE attachment_file_key = %`-queryt ois nopeita JA pakottaisi kantatasolla voimaan siivous-logiikan tekemän oletuksen, että yksi certificate_attachment liittyy korkeintaan yhteen certificateen.

Harmillisesti tää constraint pitäis lisätä kaikkiin kolmeen certificate-alitauluun, ku taulut eivät tosiaan peri constraintteja.

2023-06-29 12:17 UTC, visadb commented on server/src/main/kotlin/fi/oph/ludos/certificate/CertificateRepository.kt
> +        if (oldFileKey != null) {
Niinjoo, ja s3:n lisäksi pitää poistaa attachment-rivi myös kannasta.

Kannattaiskohan olla oma funkkari deleteAttachment, joka poistaa sekä s3-objektin että kantarivin?

2023-06-29 12:33 UTC, visadb commented on server/src/main/kotlin/fi/oph/ludos/certificate/CertificateRepository.kt
> +            s3Helper.deleteObject(oldFileKey)
Muistutus ja ehdotus huddleen liittyvästä siivoilumuutoksesta:
- siirretään tämä s3Helper.deleteObject-kutsu deleteAttachment-funktioon sql-updaten jälkeen, ja lokitetaan ja ignoroidaan sieltä tulevat virheet.
- tehdään tässä deleteAttachment(oldFileKey)-kutsu

2023-06-30 10:03 UTC, visadb commented on server/src/main/resources/db/migration/V0003_add_constraints_to_attachment_tables.sql
> +-- Create a new unique constraint on the attachment_file_key column in the certificate tables
```suggestion
-- Create a new unique constraint on the attachment_file_key column in the certificate tables.
-- We assume that attachments are never shared between certificates, so enforce that.
```

2023-07-05 11:50 UTC, visadb approved these changes

2023-07-05 12:04 UTC, merged