Notification on actions
Opetushallitus/ludos pull request #67
Opened 2023-09-25 07:28 UTC by ChristianVilen

2023-09-25 07:34 UTC, ChristianVilen commented on web/src/components/exam/formCommon/FormButtonRow.tsx
> +          {isUpdate ? t('button.tallennsa') : t('button.tallennajulkaise')}
typo

2023-09-28 12:57 UTC, visadb commented
Kommentteja lokalisaatioavaimista:
* Notifikaatio-avaimiin mukaan `notification.`, esim form.ohjeen-tallennus-luonnos-onnistui -> form.notification.ohjeen-tallennus-luonnos-onnistui
   * Ehkä tulevassa suuressa avainmylläyksessä skeema vois olla `<kokonaisuus>.<käyttökonteksti>.<tarkenne>`
* palautettu-luonnostilaan -avaimet vois olla samaa muotoa kuin muutki tallennus-avaimet, esim. `form.ohje-palautettu-luonnostilaan` -> `form.notification.ohjeen-tallennus-palautettu-luonnostilaan`
* Ehkä vois olla lisääkin hierarkiaa, esim `form.notification.ohjeen-tallennus.<viestin-tarkenne>`
* puuttuu olemassa olevan muokkaamisen tallentamisen "tallennus onnistui" -avaimet, vaik `form.notification.ohjeen-tallennus.tallennus-onnistui`

2023-09-28 12:57 UTC, visadb requested changes

2023-09-28 12:57 UTC, visadb commented on web/src/NotificationContext.tsx
> +} as const
Mä nimeäisin tän objektinkin `NotificationType` samaan tyyliin kuin types.ts:ssä on tehty.

2023-09-28 12:57 UTC, visadb commented on web/src/NotificationContext.tsx
> +  key: string
Keyn sijaan ehkä kannattais olla vaan teksti suoraan, vaik `message`. Viimeistään #68 -pullaria varten tää pitää tehdä.

2023-09-28 12:57 UTC, visadb commented on web/src/components/notification/Notification.tsx
> +  const onClose = useCallback(() => setNotification(null), [setNotification])
Oikeestaan `hideNotification` ois parempi nimi kuin `onClose`.

2023-09-29 12:48 UTC, merged