Content delete
Opetushallitus/ludos pull request #76
Opened 2023-10-19 11:46 UTC by ChristianVilen

2023-10-19 13:17 UTC, visadb commented
Muista indeksit publish_state -kolumneihin kaikkiin 9 tauluun

2023-10-24 12:07 UTC, visadb requested changes
Hyvää kamaa

2023-10-24 12:07 UTC, visadb commented on web/src/hooks/useFetch.tsx
> +  function DataWrapper({ children, errorEl }: DataWrapperProps) {
Naijs, tää DataWrapper on kiva parannus, ku ei nyt varmaan heti oteta käyttöön react routerin data loaderia.

2023-10-24 12:07 UTC, visadb commented on web/src/hooks/useFetch.tsx
> +    return <>{children}</>
Nyt `DataWrapper`in käyttäjät joutuu käyttää aina `data &&`-guardia, mikä on vähän mälsää. Oisko mahdollista, et DataWrapper sisältäis ton guardin, tähän tyyliin:

```suggestion
    } else if (data) {
      return <>{children}</>
    } else {
      return <></>
    }

    return <>{children}</>
```

2023-10-24 13:15 UTC, ChristianVilen commented on server/src/test/kotlin/fi/oph/ludos/assignment/AssignmentControllerTest.kt
> +                )
heh, mietin et miten toi copy hommeli tehtiin, mut siirryin vaa eteepäi :D

2023-10-24 13:36 UTC, visadb requested changes
Pari pikkujuttuu viel!

2023-10-24 13:36 UTC, visadb commented on playwright/helpers.ts
> +export async function assertNotification(page: Page, notificationLocalisationKey: string) {
`assertSuccessNotification`

2023-10-24 13:36 UTC, visadb commented on web/src/hooks/useFetch.tsx
> +  data?: T
Voisko tän `data`-propsun sijaan käyttää klosuurista löytyvää `data`-muuttujaa?

2023-10-25 06:40 UTC, visadb approved these changes

2023-10-26 07:48 UTC, merged