Add aine to ld instruction and certificates
Opetushallitus/ludos pull request #81
Opened 2023-10-31 08:45 UTC by ChristianVilen

todo:

- [ ] ld instruction api tests
- [ ] playwright tests

2023-11-07 12:58 UTC, visadb commented on server/src/main/kotlin/fi/oph/ludos/instruction/InstructionRepository.kt
> +        parameters.addValue("userOid", userOid)
userOidia ei käytetä instruction queryis mihinkään, niin heittäisin kaikki userOid-hommat pois koko filusta.

2023-11-07 14:01 UTC, visadb requested changes

2023-11-07 14:02 UTC, visadb commented on server/src/test/kotlin/fi/oph/ludos/certificate/Certificate.kt
> +    val content: List<T>
Nää Test*Out-luokat vois heittää roskiin ja käyttää tuotantokoodin tyyppei.

2023-11-08 06:57 UTC, visadb commented on server/src/test/kotlin/fi/oph/ludos/certificate/CertificateControllerTest.kt
> +        for (exam in exams) {
Tää looppi on hyvä, mut vois spawnaa oman testi-instanssin jokaiselle examille sen sijaan, etttä yhdessä testissä testataan kaikki examit: https://www.baeldung.com/junit5-dynamic-tests

Eli tää vois olla @TestFactory ja palauttaa listan tai streamin DynamicTest-instansseja. Ja sama muille vastaaville "testaa kaikki examit"-testeille tääällä ja InstructionControllerTestissä.

2023-11-13 14:03 UTC, visadb requested changes

2023-11-16 10:29 UTC, visadb commented on web/src/components/forms/InstructionForm.tsx
> +      state: { returnLocation: state?.returnLocation }
Oisko tässä parempi sanoa vain `{ state }`, tai säilyisikö state, jos parametrin jättää kokonaan pois navigatelta?

2023-11-16 10:57 UTC, visadb commented on playwright/all_tests/instruction/instructionFilters.spec.ts
> +const getTestId = (exam: Exam) => (exam === Exam.SUKO ? 'instruction-title' : 'instruction-body')
Miks SUKOlle käytetään eri testId:tä?

2023-11-16 12:01 UTC, visadb commented on playwright/all_tests/instruction/instructionFilters.spec.ts
> +const getTestId = (exam: Exam) => (exam === Exam.SUKO ? 'instruction-title' : 'instruction-body')
Homma taitais yksinkertaistua, jos `testNameMapping` sijaan ois `bodyTextByExam`, ja käyttäis aina testId:nä `instruction-body`?

2023-11-16 13:50 UTC, visadb commented
Ohjeet-tabin vois vielä nimetä uudestaan tässä pullarissa. "Ohjeet -välilehden uudelleen nimeäminen -> Ohjeet ja tukimateriaalit (SUKO+LD+Puhvi)"

2023-11-16 13:50 UTC, visadb commented on web/src/components/content/list/ContentListPage.tsx
> +                  teachingLanguage: languageOverrideIfSukoAssignment,
Tein tän itse.

2023-11-17 07:59 UTC, ChristianVilen commented on web/src/components/content/list/ContentListPage.tsx
> +                  teachingLanguage: languageOverrideIfSukoAssignment,
Joo vois olla hyvä! Jännittää kyl vähä useContextin käyttö kun siinä voi olla footguneja jota en ymmärrä täysin -> jotka voi johtaa et uudellee rendataa koko äppi tai jtn vastaavaa...

2023-11-20 08:26 UTC, merged