Korjaa lisää suosikiksi / poista suosikeista -nappi
Opetushallitus/ludos pull request #84
Opened 2023-11-09 13:12 UTC by visadb

DataWrapper rikkoo tämän.

2023-11-10 07:43 UTC, ChristianVilen requested changes
Olis hyvä tehdä testi jossa varmistetaan että tämä bugi ei toistu. 👍

2023-11-10 07:43 UTC, ChristianVilen commented on playwright/all_tests/instruction/instructionForm.spec.ts
> -    })
MIks tää poistettii?

2023-11-13 06:29 UTC, visadb commented on playwright/all_tests/instruction/instructionForm.spec.ts
> -    })
Commit-viesti kertoi syyn, mut tulinkin katumapäälle siitä, et nää testataan kaikille contenttypeille. Nää on aika hitaita, ja riittänee et testataan yhdelle contenttypelle eli assignmenteille. Ois tärkee yrittää pitää testit nopeina tai elämä menee kurjaks.

2023-11-13 06:33 UTC, visadb commented
> Olis hyvä tehdä testi jossa varmistetaan että tämä bugi ei toistu. 👍

Joo, ehdottomasti. Ois pitäny tehdä ennen korjausta jo ja kattoo, miksei testi huomannu.

2023-11-14 07:52 UTC, merged